#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-arel
Version  : 7.1.4
Release  : 13
URL      : https://rubygems.org/downloads/arel-7.1.4.gem
Source0  : https://rubygems.org/downloads/arel-7.1.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Arel
* http://github.com/rails/arel
## DESCRIPTION
Arel Really Exasperates Logicians

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n arel-7.1.4
gem spec %{SOURCE0} -l --ruby > rubygem-arel.gemspec

%build
export LANG=C
gem build rubygem-arel.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
arel-7.1.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/arel-7.1.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/MIT-LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/alias_predication.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/attributes.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/attributes/attribute.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/collectors/bind.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/collectors/plain_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/collectors/sql_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/compatibility/wheres.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/crud.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/delete_manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/expressions.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/factory_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/insert_manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/math.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/and.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/ascending.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/binary.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/bind_param.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/case.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/casted.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/count.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/delete_statement.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/descending.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/equality.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/extract.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/false.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/full_outer_join.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/function.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/grouping.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/in.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/infix_operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/inner_join.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/insert_statement.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/join_source.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/matches.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/named_function.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/outer_join.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/over.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/right_outer_join.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/select_core.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/select_statement.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/sql_literal.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/string_join.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/table_alias.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/terminal.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/true.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/unary.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/unary_operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/unqualified_column.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/update_statement.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/values.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/window.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/nodes/with.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/order_predications.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/predications.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/select_manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/tree_manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/update_manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/bind_substitute.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/bind_visitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/depth_first.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/dot.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/ibm_db.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/informix.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/mssql.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/mysql.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/oracle.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/oracle12.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/postgresql.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/reduce.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/sqlite.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/to_sql.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/visitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/visitors/where_sql.rb
/usr/lib64/ruby/gems/2.3.0/gems/arel-7.1.4/lib/arel/window_predications.rb
/usr/lib64/ruby/gems/2.3.0/specifications/arel-7.1.4.gemspec
